# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
 platform :ios, '11.0'

target 'SwiftMediator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftMediator
pod 'SwiftBrick'
end
