#!/bin/bash

# 计时
SECONDS=0
# 获取工程根目录

fadir()  
{  
    local this_dir=`pwd`  
    local child_dir="$1" 
    dirname "$child_dir" 
    cd $this_dir  
} 
CUR_DIR=$(cd `dirname $0` && pwd -P ) 
echo "当前文件路径 $CUR_DIR"
cd $CUR_DIR
cd ../

echo "
🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  🎉  "

    read -p "
    🚀 请输入版本号: " user_tags

    echo "
    🚀 版本号: V $user_tags "


    read -p "
    🚀 请输入更新内容（注意不要用空格）: " update_message

    echo "
    🚀 更新内容: $update_message "

echo "
🚀 即将发布 V $user_tags 版本的 $podspec, 更新: $update_message 
"
    fastlane release_pod t:$user_tags p:$podspec m:$update_message i:false
 
echo "🚀 总用时: ${SECONDS}s"
exit
 

